<script setup lang="ts">
import { computed, nextTick, onMounted, ref, watch } from 'vue'
import { ChevronDown, Loader2, RotateCcw, Sparkles } from 'lucide-vue-next'
import { useRouter } from 'vue-router'
import { useUiStore } from '@/stores/ui'
import { useProjectStore } from '@/stores/project'
import { confirmWorkflowPlan, getDagDraft, previewWorkflowPlan, saveDagDraft, validateWorkflowPlan } from '@/api/workflows'
import { ApiError } from '@/api/client'
import type { CreateAnalysisRunRequest, WorkflowCapabilities, WorkflowCanvasEdge, WorkflowCanvasNode, WorkflowPlanPreview } from '@/api/types'
import { PROXY_QUALITY_OPTIONS } from '@/shared/constants'

const props = defineProps<{ projectId: string; hasAssets: boolean }>()
const router = useRouter(); const uiStore = useUiStore(); const projectStore = useProjectStore()
const proxyQuality = ref<CreateAnalysisRunRequest['quality']>('1080P'); const goal = ref('')
const autoMode = ref(false); const capabilities = ref<WorkflowCapabilities>({ vlmAnalysis: true, sourceTranscription: true, subtitles: true, bgm: true })
const plan = ref<WorkflowPlanPreview | null>(null); const loading = ref(false); const launching = ref(false); const useDefault = ref(false)
const validation = ref<{ valid: boolean; errors: string[] } | null>(null); const canvasRef = ref<HTMLElement | null>(null)
const selectedNode = ref<string | null>(null); const selectedEdgeId = ref<string | null>(null); const removedNodes = ref(new Set<string>()); const removedEdges = ref(new Set<string>()); const addedEdges = ref<WorkflowCanvasEdge[]>([])
const positions = ref<Record<string, { x: number; y: number }>>({}); const connecting = ref<{ from: string; x: number; y: number } | null>(null)
const draggedCapability = ref<string | null>(null); const pendingCapabilityDrop = ref<{ key: string; x: number; y: number } | null>(null); const suppressNextClick = ref(false)
const zoom = ref(0.86); const viewportHeight = ref(560)
const draftStatus = ref<'idle' | 'saving' | 'saved' | 'error' | 'conflict'>('idle'); const draftRevision = ref(0); let draftTimer: ReturnType<typeof setTimeout> | null = null
const draftId = 'dynamic-dag'
const capabilityItems = [
  { key: 'vlmAnalysis', label: '视觉语义分析' }, { key: 'sourceTranscription', label: '源音频转写' }, { key: 'subtitles', label: '字幕编排' }, { key: 'bgm', label: '背景音乐' },
]
const canvasNodes = computed(() => (plan.value?.canvas.nodes ?? []).filter(node => !removedNodes.value.has(node.id)))
const localEdges = computed(() => [ ...(plan.value?.canvas.edges ?? []).filter(edge => !removedEdges.value.has(edge.id) && nodeById.value.has(edge.from) && nodeById.value.has(edge.to)), ...addedEdges.value.filter(edge => nodeById.value.has(edge.from) && nodeById.value.has(edge.to)) ])
const nodeById = computed(() => new Map(canvasNodes.value.map(node => [node.id, node])))
const canvasSize = computed(() => ({ width: Math.max(1100, ...canvasNodes.value.map(node => (positions.value[node.id]?.x ?? node.x) + 190)), height: Math.max(520, ...canvasNodes.value.map(node => (positions.value[node.id]?.y ?? node.y) + 110)) }))
const scaledCanvasSize = computed(() => ({ width: canvasSize.value.width * zoom.value, height: canvasSize.value.height * zoom.value })); const canPreview = computed(() => props.hasAssets && !loading.value && !launching.value)

function initializeCanvas(): void {
  const incoming = new Map(canvasNodes.value.map(node => [node.id, 0])); const outgoing = new Map(canvasNodes.value.map(node => [node.id, [] as string[]])); const ids = new Set(canvasNodes.value.map(node => node.id))
  for (const edge of plan.value?.canvas.edges ?? []) if (ids.has(edge.from) && ids.has(edge.to)) { incoming.set(edge.to, (incoming.get(edge.to) ?? 0) + 1); outgoing.get(edge.from)?.push(edge.to) }
  const rank = new Map<string, number>(); const queue = canvasNodes.value.filter(node => (incoming.get(node.id) ?? 0) === 0).map(node => node.id); queue.forEach(id => rank.set(id, 0))
  for (let i = 0; i < queue.length; i += 1) { const id = queue[i]; if (!id) continue; for (const next of outgoing.get(id) ?? []) { rank.set(next, Math.max(rank.get(next) ?? 0, (rank.get(id) ?? 0) + 1)); incoming.set(next, (incoming.get(next) ?? 1) - 1); if (incoming.get(next) === 0) queue.push(next) } }
  const groups = new Map<number, WorkflowCanvasNode[]>(); for (const node of canvasNodes.value) { const layer = rank.get(node.id) ?? 0; if (!groups.has(layer)) groups.set(layer, []); groups.get(layer)?.push(node) }
  const next: Record<string, { x: number; y: number }> = {}; for (const [layer, nodes] of [...groups.entries()].sort((a, b) => a[0] - b[0])) { const ordered = nodes.sort((a, b) => (a.assetIndex ?? 999) - (b.assetIndex ?? 999) || a.id.localeCompare(b.id)); const offset = Math.max(0, (8 - ordered.length) * 46); ordered.forEach((node, index) => { next[node.id] = { x: 34 + layer * 220, y: 28 + offset + index * 112 } }) }
  positions.value = next; if (!pendingCapabilityDrop.value) { removedNodes.value = new Set(); removedEdges.value = new Set(); addedEdges.value = [] }; selectedNode.value = null; selectedEdgeId.value = null; validation.value = null
}
function position(id: string): { x: number; y: number } { const node = nodeById.value.get(id); return node ? positions.value[id] ?? { x: node.x, y: node.y } : { x: 0, y: 0 } }
function point(node: WorkflowCanvasNode, side: 'left' | 'right'): { x: number; y: number } { const pos = position(node.id); return { x: pos.x + (side === 'right' ? 144 : 0), y: pos.y + 25 } }
function edgePath(edge: WorkflowCanvasEdge) { const from = nodeById.value.get(edge.from); const to = nodeById.value.get(edge.to); if (!from || !to) return { x1: 0, y1: 0, x2: 0, y2: 0 }; const a = point(from, 'right'); const b = point(to, 'left'); return { x1: a.x, y1: a.y, x2: b.x, y2: b.y } }
function clearSelection(): void { selectedNode.value = null; selectedEdgeId.value = null; connecting.value = null }
function clickNode(node: WorkflowCanvasNode): void { if (suppressNextClick.value) return; if (selectedNode.value === node.id) { removedNodes.value = new Set([...removedNodes.value, node.id]); selectedNode.value = null; validation.value = null } else { selectedNode.value = node.id; selectedEdgeId.value = null } }
function clickEdge(edge: WorkflowCanvasEdge): void { if (selectedEdgeId.value === edge.id) { if (addedEdges.value.some(item => item.id === edge.id)) addedEdges.value = addedEdges.value.filter(item => item.id !== edge.id); else removedEdges.value = new Set([...removedEdges.value, edge.id]); selectedEdgeId.value = null } else { selectedEdgeId.value = edge.id; selectedNode.value = null } }
function startNodeDrag(node: WorkflowCanvasNode, event: PointerEvent): void {
  if ((event.target as HTMLElement).dataset.port) return; const canvas = canvasRef.value; if (!canvas) return; const rect = canvas.getBoundingClientRect(); const current = position(node.id); const px = (event.clientX - rect.left + canvas.scrollLeft) / zoom.value; const py = (event.clientY - rect.top + canvas.scrollTop) / zoom.value; const ox = px - current.x; const oy = py - current.y; let moved = false
  const move = (e: PointerEvent) => { const x = (e.clientX - rect.left + canvas.scrollLeft) / zoom.value; const y = (e.clientY - rect.top + canvas.scrollTop) / zoom.value; if (Math.abs(x - px) + Math.abs(y - py) > 4) { moved = true; suppressNextClick.value = true }; positions.value[node.id] = { x: Math.max(8, x - ox), y: Math.max(8, y - oy) } }
  const end = () => { window.removeEventListener('pointermove', move); window.removeEventListener('pointerup', end); if (moved) window.setTimeout(() => { suppressNextClick.value = false }, 0) }; window.addEventListener('pointermove', move); window.addEventListener('pointerup', end)
}
function startConnection(node: WorkflowCanvasNode, event: PointerEvent): void { event.stopPropagation(); const canvas = canvasRef.value; if (!canvas) return; const rect = canvas.getBoundingClientRect(); connecting.value = { from: node.id, x: (event.clientX - rect.left + canvas.scrollLeft) / zoom.value, y: (event.clientY - rect.top + canvas.scrollTop) / zoom.value }; const move = (e: PointerEvent) => { connecting.value = { from: node.id, x: (e.clientX - rect.left + canvas.scrollLeft) / zoom.value, y: (e.clientY - rect.top + canvas.scrollTop) / zoom.value } }; const end = () => { window.removeEventListener('pointermove', move); window.removeEventListener('pointerup', end) }; window.addEventListener('pointermove', move); window.addEventListener('pointerup', end) }
function finishConnection(node: WorkflowCanvasNode, event: PointerEvent): void { event.stopPropagation(); if (!connecting.value || connecting.value.from === node.id) { connecting.value = null; return }; const from = connecting.value.from; const id = `${from}->${node.id}`; if (!localEdges.value.some(edge => edge.id === id)) addedEdges.value = [...addedEdges.value, { id, from, to: node.id, dependencyType: 'REQUIRED', deletable: true }]; connecting.value = null }
function dragCapabilityStart(key: string): void { draggedCapability.value = key }
function capabilityNodeKey(key: string): string { return key === 'sourceTranscription' ? 'source_transcribe' : key === 'subtitles' ? 'subtitle_compose' : key === 'bgm' ? 'bgm_select' : 'vision_vlm_analyze' }
function dropCapability(event: DragEvent): void { if (!draggedCapability.value) return; const canvas = canvasRef.value; if (!canvas) return; const rect = canvas.getBoundingClientRect(); const key = draggedCapability.value; pendingCapabilityDrop.value = { key, x: (event.clientX - rect.left + canvas.scrollLeft) / zoom.value, y: (event.clientY - rect.top + canvas.scrollTop) / zoom.value }; capabilities.value = { ...capabilities.value, [key]: true }; draggedCapability.value = null; void preview(false, true) }
function zoomIn(): void { zoom.value = Math.min(1.35, Number((zoom.value + 0.1).toFixed(2))) }; function zoomOut(): void { zoom.value = Math.max(0.55, Number((zoom.value - 0.1).toFixed(2))) }; function fitCanvas(): void { zoom.value = 0.86 }

async function preview(useDefaultPlan = false, fromUser = false): Promise<void> { if (!canPreview.value) return; loading.value = true; useDefault.value = useDefaultPlan; try { plan.value = await previewWorkflowPlan(props.projectId, { assetIds: projectStore.assets.map(asset => asset.id), quality: proxyQuality.value, goal: goal.value.trim() || undefined, autoMode: autoMode.value, capabilities: fromUser ? capabilities.value : undefined, useDefault: useDefaultPlan }); capabilities.value = plan.value.intent.capabilities; await nextTick(); initializeCanvas(); if (pendingCapabilityDrop.value) { const dropped = pendingCapabilityDrop.value; const node = canvasNodes.value.find(item => item.logicalNodeKey === capabilityNodeKey(dropped.key)); if (node) { positions.value[node.id] = { x: dropped.x, y: dropped.y }; removedEdges.value = new Set([...removedEdges.value, ...plan.value.canvas.edges.filter(edge => edge.from === node.id || edge.to === node.id).map(edge => edge.id)]) }; pendingCapabilityDrop.value = null } } catch (error) { uiStore.showToast(error instanceof Error ? error.message : '生成候选流程图失败', 'error') } finally { loading.value = false } }
function draftPayload() { return { version: 1, draftRevision: draftRevision.value, goal: goal.value, quality: proxyQuality.value, autoMode: autoMode.value, capabilities: capabilities.value, useDefault: useDefault.value, plan: plan.value, positions: positions.value, removedNodeIds: [...removedNodes.value], removedEdgeIds: [...removedEdges.value], addedEdges: addedEdges.value } }
function scheduleDraftSave(): void {
  if (!plan.value || !props.hasAssets) return
  draftStatus.value = 'saving'
  if (draftTimer) clearTimeout(draftTimer)
  draftTimer = setTimeout(async () => {
    try { const result = await saveDagDraft(props.projectId, draftId, draftPayload()); draftRevision.value = result.revision; draftStatus.value = 'saved' } catch (error) { draftStatus.value = error instanceof ApiError && error.status === 409 ? 'conflict' : 'error' }
  }, 700)
}
async function restoreDraft(): Promise<void> {
  try {
    const draft = await getDagDraft<ReturnType<typeof draftPayload>>(props.projectId, draftId)
    if (!draft || draft.version !== 1) return
    draftRevision.value = Number(draft.draftRevision ?? 0)
    goal.value = draft.goal ?? ''; proxyQuality.value = draft.quality ?? proxyQuality.value; autoMode.value = Boolean(draft.autoMode)
    capabilities.value = draft.capabilities ?? capabilities.value; useDefault.value = Boolean(draft.useDefault)
    if (draft.plan) { plan.value = draft.plan; positions.value = draft.positions ?? {}; await nextTick(); initializeCanvas(); positions.value = draft.positions ?? positions.value; removedNodes.value = new Set(draft.removedNodeIds ?? []); removedEdges.value = new Set(draft.removedEdgeIds ?? []); addedEdges.value = draft.addedEdges ?? [] }
    draftStatus.value = 'saved'
  } catch (error) { if (!(error instanceof ApiError && error.status === 404)) draftStatus.value = 'error' }
}
watch([goal, proxyQuality, autoMode, capabilities, plan, positions, removedNodes, removedEdges, addedEdges], scheduleDraftSave, { deep: true })
onMounted(() => { void restoreDraft() })
async function confirm(): Promise<void> { if (!plan.value || launching.value) return; launching.value = true; try { const request = { assetIds: projectStore.assets.map(asset => asset.id), quality: proxyQuality.value, goal: goal.value.trim() || undefined, autoMode: autoMode.value, capabilities: capabilities.value, useDefault: useDefault.value, removedNodeIds: [...removedNodes.value], removedEdgeIds: [...removedEdges.value], addedEdges: addedEdges.value }; validation.value = await validateWorkflowPlan(props.projectId, request); if (!validation.value.valid) { uiStore.showToast(validation.value.errors.join('；'), 'error'); return }; const result = await confirmWorkflowPlan(props.projectId, request); uiStore.showToast('已确认流程图，Workflow 已启动', 'success'); router.push(`/projects/${props.projectId}/runs/${result.workflowRunId}`) } catch (error) { uiStore.showToast(error instanceof Error ? error.message : '确认流程失败', 'error') } finally { launching.value = false } }
</script>

<template>
  <div class="card" @click="clearSelection">
    <div class="flex items-start justify-between gap-3 mb-4"><div><p class="section-eyebrow mb-1">DYNAMIC WORKFLOW</p><h2 class="section-heading flex items-center gap-2"><Sparkles class="w-5 h-5 text-accent" />动态流程编排</h2><p class="text-xs text-surface-500 mt-1">先描述需求，由 LLM 生成初版 DAG，再把能力卡片拖到画布并自行连接。</p></div></div>
    <div v-if="!hasAssets" class="mb-4 rounded-lg border border-warning/20 bg-warning/10 px-3 py-2.5 text-sm text-warning">请先上传视频素材，再生成动态流程图</div>
    <div class="grid gap-4 md:grid-cols-2"><div><label class="form-label">自然语言需求（包含时长）</label><textarea v-model="goal" class="input-field min-h-24" maxlength="500" placeholder="例如：两个视频做成节奏快、突出人物和旅行高光的 30 秒短片"></textarea></div><div><label class="form-label">输出清晰度</label><select v-model="proxyQuality" class="select-field"><option v-for="opt in PROXY_QUALITY_OPTIONS" :key="opt.value" :value="opt.value">{{ opt.label }}</option></select><p class="mt-2 text-xs text-surface-500">时长请直接写在需求中，例如“30秒”“1分钟”或“半分钟”。</p></div></div>
    <div class="mt-4 flex flex-wrap gap-2"><button class="btn-primary" :disabled="!canPreview" @click.stop="preview(false)"><Loader2 v-if="loading" class="h-4 w-4 animate-spin" /><Sparkles v-else class="h-4 w-4" />生成候选流程图</button><button class="btn-secondary" :disabled="!canPreview" @click.stop="preview(true)"><RotateCcw class="h-4 w-4" />使用默认 DAG</button></div>
    <div v-if="plan" class="mt-5 rounded-xl border border-surface-700 bg-surface-950/60 p-3" @click.stop>
      <div class="mb-3 flex flex-wrap items-center justify-between gap-2"><div><p class="text-sm font-semibold text-surface-100">{{ plan.llmUsed ? 'LLM 候选 DAG' : plan.defaultSelected ? '系统默认 DAG' : '候选动态 DAG' }}</p><p class="text-xs text-surface-500">{{ plan.intent.explanation }}</p></div><div class="flex items-center gap-2"><span v-if="draftStatus === 'saving'" class="text-[11px] text-surface-500">正在自动保存草稿…</span><span v-else-if="draftStatus === 'saved'" class="text-[11px] text-emerald-400">草稿已自动保存（版本 {{ draftRevision }}）</span><span v-else-if="draftStatus === 'conflict'" class="text-[11px] text-warning">草稿版本冲突，请刷新后再编辑</span><span v-else-if="draftStatus === 'error'" class="text-[11px] text-warning">草稿保存失败，仍保留当前页面内容</span><button class="btn-secondary text-xs" @click="preview(true)"><RotateCcw class="h-3.5 w-3.5" />恢复默认 DAG</button></div></div>
      <div class="mb-3 rounded-lg border border-surface-800 bg-surface-900/70 p-3"><div class="mb-2 flex items-center justify-between"><span class="text-xs font-semibold text-surface-200">可选能力卡片</span><span class="text-[11px] text-surface-500">全部能力都在这里，直接拖到画布位置</span></div><div class="grid gap-2 sm:grid-cols-4"><div v-for="item in capabilityItems" :key="item.key" draggable="true" class="cursor-grab rounded border border-surface-700 bg-surface-800 px-2.5 py-1.5 active:cursor-grabbing" @dragstart="dragCapabilityStart(item.key)"><p class="text-xs text-surface-100">{{ item.label }}</p></div></div><div class="mt-3 rounded border border-surface-700 bg-surface-950/60 px-3 py-2"><p class="text-xs font-semibold text-surface-300">已选能力</p><p class="mt-1 text-xs text-surface-500">{{ capabilityItems.filter(item => capabilities[item.key as keyof WorkflowCapabilities]).map(item => item.label).join('、') }}</p></div></div>
      <div class="mb-2 flex flex-wrap items-center justify-between gap-2"><div class="flex items-center gap-2 text-xs text-surface-400"><button class="btn-secondary px-2 py-1 text-xs" @click="zoomOut">−</button><span class="min-w-12 text-center">{{ Math.round(zoom * 100) }}%</span><button class="btn-secondary px-2 py-1 text-xs" @click="zoomIn">+</button><button class="btn-secondary text-xs" @click="fitCanvas">适应画布</button></div><label class="flex items-center gap-2 text-xs text-surface-400">画布高度 <input v-model.number="viewportHeight" type="range" min="360" max="900" step="20" /><span>{{ viewportHeight }}px</span></label></div>
      <div ref="canvasRef" class="relative overflow-auto rounded-lg border border-surface-800 bg-surface-950" :style="{ height: `${viewportHeight}px` }" @dragover.prevent @drop.prevent="dropCapability" @pointerdown="clearSelection"><div class="relative" :style="{ width: `${scaledCanvasSize.width}px`, height: `${scaledCanvasSize.height}px` }"><div class="absolute left-0 top-0 origin-top-left" :style="{ width: `${canvasSize.width}px`, height: `${canvasSize.height}px`, transform: `scale(${zoom})` }"><svg class="absolute inset-0 h-full w-full" :width="canvasSize.width" :height="canvasSize.height"><line v-for="edge in localEdges" :key="edge.id" v-bind="edgePath(edge)" :stroke="selectedEdgeId === edge.id ? '#f97316' : '#38bdf8'" :stroke-width="selectedEdgeId === edge.id ? 5 : 2.5" class="cursor-pointer" style="pointer-events: stroke" @pointerdown.stop="clickEdge(edge)" /><line v-if="connecting" :x1="point(nodeById.get(connecting.from)!, 'right').x" :y1="point(nodeById.get(connecting.from)!, 'right').y" :x2="connecting.x" :y2="connecting.y" stroke="#f97316" stroke-width="2" /></svg><div v-for="node in canvasNodes" :key="node.id" class="absolute w-36 rounded-lg border px-2 py-1.5 shadow-lg" :class="[node.optional ? 'border-accent/40 bg-accent/10' : 'border-surface-700 bg-surface-800', selectedNode === node.id ? 'ring-2 ring-accent/60' : '', connecting?.from === node.id ? 'ring-2 ring-orange-400' : '']" :style="{ left: `${position(node.id).x}px`, top: `${position(node.id).y}px` }" @pointerdown.stop="startNodeDrag(node, $event)" @click.stop="clickNode(node)"><button v-if="node.logicalNodeKey !== 'video_probe'" data-port="true" type="button" class="absolute -left-2 top-5 h-3.5 w-3.5 rounded-full border-2 border-sky-300 bg-surface-950" title="输入端口" @pointerup.stop="finishConnection(node, $event)"></button><button data-port="true" type="button" class="absolute -right-2 top-5 h-3.5 w-3.5 rounded-full border-2 border-orange-300 bg-surface-950" title="输出端口" @pointerdown.stop="startConnection(node, $event)"></button><p class="text-[11px] font-semibold leading-4 text-surface-100">{{ node.label }}</p><p class="mt-0.5 text-[10px] text-surface-400">{{ node.scope === 'ASSET' ? `素材 ${Number(node.assetIndex) + 1}` : '工作流' }}</p></div></div></div></div>
      <div v-if="validation && !validation.valid" class="mt-3 rounded-lg border border-danger/30 bg-danger/10 p-3 text-xs text-danger-light"><p class="font-semibold">当前流程图无法执行</p><p v-for="error in validation.errors" :key="error" class="mt-1">{{ error }}</p></div><div class="mt-3 flex flex-wrap items-center justify-between gap-2"><div class="flex items-center gap-3"><span class="text-[11px] text-surface-500">拖动超过 4px 才会移动卡片；卡片和连线第一次点击高亮、第二次点击删除。</span><label class="flex items-center gap-2 text-xs text-surface-400">执行模式 <select v-model="autoMode" class="select-field w-auto py-1 text-xs"><option :value="false">半自动（保留人工审核）</option><option :value="true">全自动（跳过审核 Gate）</option></select></label></div><button class="btn-primary" :disabled="!plan || launching" @click="confirm"><Loader2 v-if="launching" class="h-4 w-4 animate-spin" /><ChevronDown v-else class="h-4 w-4" />确认流程并开始</button></div>
    </div>
  </div>
</template>
