CREATE TABLE agent_trace_events (
    id              VARCHAR(40) NOT NULL,
    created_at      DATETIME(6) NOT NULL,
    updated_at      DATETIME(6) NOT NULL,
    version         BIGINT NOT NULL DEFAULT 0,
    event_type      VARCHAR(80) NOT NULL,
    trace_id        VARCHAR(80) NOT NULL,
    session_id      VARCHAR(80) NULL,
    turn_id         VARCHAR(80) NULL,
    plan_id         VARCHAR(80) NULL,
    workflow_run_id VARCHAR(40) NULL,
    task_run_id     VARCHAR(40) NULL,
    message_id      VARCHAR(80) NULL,
    execution_id    VARCHAR(80) NULL,
    agent_name      VARCHAR(120) NULL,
    tool_name       VARCHAR(120) NULL,
    status          VARCHAR(30) NULL,
    occurred_at     DATETIME(6) NOT NULL,
    payload_json    LONGTEXT NULL,
    PRIMARY KEY (id),
    INDEX idx_trace_workflow_time (workflow_run_id, occurred_at),
    INDEX idx_trace_session_time (session_id, occurred_at),
    INDEX idx_trace_trace_time (trace_id, occurred_at),
    INDEX idx_trace_event_type (event_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
